CREATE TABLE IF NOT EXISTS COMPANY (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    `number` VARCHAR(255) NOT NULL,
    country_code VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    zip VARCHAR(255) NOT NULL,
    //ice_number VARCHAR(255) NOT NULL
    num VARCHAR(255) NOT NULL
);